[features]
seeds = false
skip-lint = false

[programs.localnet]
auth_api = "8sfYb3xx2gNtwtuwg6UzcpPx4FZK1WJJbYZbPgy1hrQJ"

[programs.devnet]
auth_api = "8sfYb3xx2gNtwtuwg6UzcpPx4FZK1WJJbYZbPgy1hrQJ"

[programs.mainnet]
auth_api = "8sfYb3xx2gNtwtuwg6UzcpPx4FZK1WJJbYZbPgy1hrQJ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "mainnet"
wallet = "/Users/nielsoskam/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
